### ISSUE TITLE
I can get the result when I run inference_demo.py, but I get an error when training my data.CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by caoccp** [WXinlong/SOLO#123]
Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main()
  File "tools/train.py", line 121, in main
    timestamp=timestamp)
  File "/home/user/iridium/SOLO/mmdet/apis/train.py", line 111, in train_detector
    timestamp=timestamp)
  File "/home/user/iridium/SOLO/mmdet/apis/train.py", line 297, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/user/anaconda/envs/SOLO/lib/python3.7/site-packages/mmcv/runner/runner.py", line 364, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/user/anaconda/envs/SOLO/lib/python3.7/site-packages/mmcv/runner/runner.py", line 268, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/user/iridium/SOLO/mmdet/apis/train.py", line 78, in batch_processor
    losses = model(**data)
  File "/home/user/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/iridium/SOLO/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/user/iridium/SOLO/mmdet/models/detectors/base.py", line 142, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/user/iridium/SOLO/mmdet/models/detectors/single_stage_ins.py", line 78, in forward_train
    *loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/home/user/iridium/SOLO/mmdet/models/anchor_heads/solo_head.py", line 229, in loss
    loss_cate = self.loss_cate(flatten_cate_preds, flatten_cate_labels, avg_factor=num_ins + 1)
  File "/home/user/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/iridium/SOLO/mmdet/models/losses/focal_loss.py", line 79, in forward
    avg_factor=avg_factor)
  File "/home/user/iridium/SOLO/mmdet/models/losses/focal_loss.py", line 37, in sigmoid_focal_loss
    loss = _sigmoid_focal_loss(pred, target, gamma, alpha)
  File "/home/user/iridium/SOLO/mmdet/ops/sigmoid_focal_loss/sigmoid_focal_loss.py", line 19, in forward
    gamma, alpha)
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at mmdet/ops/sigmoid_focal_loss/src/sigmoid_focal_loss_cuda.cu:128

I have tried many combinations of pytorch and CUDA, but they have not been resolved.

**Comment by WXinlong** [comment]
@caoccp  What have you tried? We prefer using PyTorch 1.4.

**Comment by caoccp** [comment]
> @caoccp你试过什么？我们更喜欢使用 PyTorch 1.4。

Thanks, I have solved this problem
